import re

raw_text = r"""alphabe["0-text"] = alphabet["g2-48"]
alphabe["1-text"] = alphabet["g2-49"]
alphabe["2-text"] = alphabet["g2-50"]
alphabe["3-text"] = alphabet["g2-51"]
alphabe["4-text"] = alphabet["g2-52"]
alphabe["5-text"] = alphabet["g2-53"]
alphabe["6-text"] = alphabet["g2-54"]
alphabe["7-text"] = alphabet["g2-55"]
alphabe["8-text"] = alphabet["g2-56"]
alphabe["9-text"] = alphabet["g2-57"]
alphabe["A-text"] = alphabet["g2-65"]
alphabe["B-text"] = alphabet["g2-66"]
alphabe["C-text"] = alphabet["g2-67"]
alphabe["D-text"] = alphabet["g2-68"]
alphabe["E-text"] = alphabet["g2-69"]
alphabe["F-text"] = alphabet["g2-70"]
alphabe["G-text"] = alphabet["g2-71"]
alphabe["H-text"] = alphabet["g2-72"]
alphabe["I-text"] = alphabet["g2-73"]
alphabe["J-text"] = alphabet["g2-74"]
alphabe["K-text"] = alphabet["g2-75"]
alphabe["L-text"] = alphabet["g2-76"]
alphabe["M-text"] = alphabet["g2-77"]
alphabe["N-text"] = alphabet["g2-78"]
alphabe["O-text"] = alphabet["g2-79"]
alphabe["P-text"] = alphabet["g2-80"]
alphabe["Q-text"] = alphabet["g2-81"]
alphabe["R-text"] = alphabet["g2-82"]
alphabe["S-text"] = alphabet["g2-83"]
alphabe["T-text"] = alphabet["g2-84"]
alphabe["U-text"] = alphabet["g2-85"]
alphabe["V-text"] = alphabet["g2-86"]
alphabe["W-text"] = alphabet["g2-87"]
alphabe["X-text"] = alphabet["g2-88"]
alphabe["Y-text"] = alphabet["g2-89"]
alphabe["Z-text"] = alphabet["g2-90"]
alphabe["a-text"] = alphabet["g2-97"]
alphabe["b-text"] = alphabet["g2-98"]
alphabe["c-text"] = alphabet["g2-99"]
alphabe["d-text"] = alphabet["g2-100"]
alphabe["e-text"] = alphabet["g2-101"]
alphabe["f-text"] = alphabet["g2-102"]
alphabe["g-text"] = alphabet["g2-103"]
alphabe["h-text"] = alphabet["g2-104"]
alphabe["i-text"] = alphabet["g2-105"]
alphabe["j-text"] = alphabet["g2-106"]
alphabe["k-text"] = alphabet["g2-107"]
alphabe["l-text"] = alphabet["g2-108"]
alphabe["m-text"] = alphabet["g2-109"]
alphabe["n-text"] = alphabet["g2-110"]
alphabe["o-text"] = alphabet["g2-111"]
alphabe["p-text"] = alphabet["g2-112"]
alphabe["q-text"] = alphabet["g2-113"]
alphabe["r-text"] = alphabet["g2-114"]
alphabe["s-text"] = alphabet["g2-115"]
alphabe["t-text"] = alphabet["g2-116"]
alphabe["u-text"] = alphabet["g2-117"]
alphabe["v-text"] = alphabet["g2-118"]
alphabe["w-text"] = alphabet["g2-119"]
alphabe["x-text"] = alphabet["g2-120"]
alphabe["y-text"] = alphabet["g2-121"]
alphabe["z-text"] = alphabet["g2-122"]
alphabe["--text"] = alphabet["g2-45"]
alphabe["=-text"] = alphabet["g2-61"]
alphabe["!-text"] = alphabet["g2-33"]
alphabe["*-text"] = alphabet["g2-42"]
alphabe["(-text"] = alphabet["g2-40"]
alphabe[")-text"] = alphabet["g2-41"]
alphabe["+-text"] = alphabet["g2-43"]
alphabe[",-text"] = alphabet["g2-44"]
alphabe[".-text"] = alphabet["g2-46"]"""
text = (
    raw_text.replace("[", "")
    .replace("]", "")
    .replace("alphabet", "")
    .replace("alphabe", "")
    .replace("-text", "")
    .replace(" =", ":")
    .replace("\n", ",")
)
text = "{" + re.sub("g[0-9]{1}-", "", text) + "}"
alphabet = eval(text)
print(alphabet)
